name: Test & Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"

      - name: Install dependencies
        run: make install

      - name: Build applications
        run: make build

      - name: Run tests
        run: make test
