name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          sparse-checkout: "server"

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build application
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          sparse-checkout: "client"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Run tests
        run: npm test
